### ISSUE TITLE
Kaldi MFCC to TFRecords

### ISSUE THREAD

**Issue by asadullah797** [JRMeyer/kaldi-tf#1]
Thank you for your efforts for exporting kaldi models to TF.
I have one question?  Can kaldi MFCC be coverted to TFRecords.
I want to export Kaldi MFCC to TFRecords do some processing and then export to Kaldi.
Thanks

**Comment by JRMeyer** [comment]
Hi Asadullah, 

These scripts are exactly for for taking features and exporting them into TF.

The assumption is that your features are already in [Nnet3Eg](https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3/nnet-example.cc) format. They can be MFCC or PLP or whatever you want.

However, going straight from MFCC ark files to TFrecords is not something I have time to work on, unfortunately.

If you'd like to write that script (or atleast MFCC ark --> CSV ), then I'd love to add it here as a resource.

-josh
