### ISSUE TITLE
How to use in decode stage

### ISSUE THREAD

**Issue by panxin801** [JRMeyer/kaldi-tf#2]
Hello sir, I am working on the similar work like yours. But I have no idea on how to use tensorflow in kaldi decoding stage. Can you help me with that? Thank you foe the help and time.

**Comment by JRMeyer** [comment]
If you're looking to use tensorflow as an acoustic model, this code is useful to get data in the right format, but this code doesn't have examples for acoustic models. I'd recommend pytorch-kaldi instead (not tensorflow, but similar functionality)

**Comment by panxin801** [comment]
Hello sir,
Yeah I know pytorch-kaldi, I will try and thanks for your advice.
